from types  import FunctionType, MethodType
from typing import Union

def get_handler_name(input_string: str):
    def normalizer():
        return "".join(l if l.islower() else "_" + l.lower() for l in input_string)
        
    return normalizer().removesuffix("handler").strip("_")

class BaseHandler:
    def __init__(self, func: Union[FunctionType, MethodType]) -> None:
        self.name = get_handler_name(self.__class__.__name__)
        self.func = func

class MessageHandler(BaseHandler):...
class EditedMessageHandler(BaseHandler):...
class ChannelPostHandler(BaseHandler):...
class EditedChannelPostHandler(BaseHandler):...
class InlineQueryHandler(BaseHandler):...
class ChosenInlineResultHandler(BaseHandler):...
class CallbackQueryHandler(BaseHandler):...
class ShippingQueryHandler(BaseHandler):...
class PreCheckoutQueryHandler(BaseHandler):...
class PollHandler(BaseHandler):...
class PollAnswerHandler(BaseHandler):...
class MyChatMemberHandler(BaseHandler):...
class ChatMemberHandler(BaseHandler):...
class ChatJoinRequestHandler(BaseHandler):...