from .Update import Update
from .WebhookInfo import WebhookInfo
from .User import User
from .Chat import Chat
from .Message import Message
from .MessageId import MessageId
from .MessageEntity import MessageEntity
from .PhotoSize import PhotoSize
from .Animation import Animation
from .Audio import Audio
from .Document import Document
from .Video import Video
from .VideoNote import VideoNote
from .Voice import Voice
from .Contact import Contact
from .Dice import Dice
from .PollOption import PollOption
from .PollAnswer import PollAnswer
from .Poll import Poll
from .Location import Location
from .Venue import Venue
from .WebAppData import WebAppData
from .ProximityAlertTriggered import ProximityAlertTriggered
from .MessageAutoDeleteTimerChanged import MessageAutoDeleteTimerChanged
from .ForumTopicCreated import ForumTopicCreated
from .ForumTopicClosed import ForumTopicClosed
from .ForumTopicEdited import ForumTopicEdited
from .ForumTopicReopened import ForumTopicReopened
from .GeneralForumTopicHidden import GeneralForumTopicHidden
from .GeneralForumTopicUnhidden import GeneralForumTopicUnhidden
from .UserShared import UserShared
from .ChatShared import ChatShared
from .WriteAccessAllowed import WriteAccessAllowed
from .VideoChatScheduled import VideoChatScheduled
from .VideoChatStarted import VideoChatStarted
from .VideoChatEnded import VideoChatEnded
from .VideoChatParticipantsInvited import VideoChatParticipantsInvited
from .UserProfilePhotos import UserProfilePhotos
from .File import File
from .WebAppInfo import WebAppInfo
from .ReplyKeyboardMarkup import ReplyKeyboardMarkup
from .KeyboardButton import KeyboardButton
from .KeyboardButtonRequestUser import KeyboardButtonRequestUser
from .KeyboardButtonRequestChat import KeyboardButtonRequestChat
from .KeyboardButtonPollType import KeyboardButtonPollType
from .ReplyKeyboardRemove import ReplyKeyboardRemove
from .InlineKeyboardMarkup import InlineKeyboardMarkup
from .InlineKeyboardButton import InlineKeyboardButton
from .LoginUrl import LoginUrl
from .SwitchInlineQueryChosenChat import SwitchInlineQueryChosenChat
from .CallbackQuery import CallbackQuery
from .ForceReply import ForceReply
from .ChatPhoto import ChatPhoto
from .ChatInviteLink import ChatInviteLink
from .ChatAdministratorRights import ChatAdministratorRights
from .ChatMember import ChatMember
from .ChatMemberOwner import ChatMemberOwner
from .ChatMemberAdministrator import ChatMemberAdministrator
from .ChatMemberMember import ChatMemberMember
from .ChatMemberRestricted import ChatMemberRestricted
from .ChatMemberLeft import ChatMemberLeft
from .ChatMemberBanned import ChatMemberBanned
from .ChatMemberUpdated import ChatMemberUpdated
from .ChatJoinRequest import ChatJoinRequest
from .ChatPermissions import ChatPermissions
from .ChatLocation import ChatLocation
from .ForumTopic import ForumTopic
from .BotCommand import BotCommand
from .BotCommandScope import BotCommandScope
from .BotCommandScopeDefault import BotCommandScopeDefault
from .BotCommandScopeAllPrivateChats import BotCommandScopeAllPrivateChats
from .BotCommandScopeAllGroupChats import BotCommandScopeAllGroupChats
from .BotCommandScopeAllChatAdministrators import BotCommandScopeAllChatAdministrators
from .BotCommandScopeChat import BotCommandScopeChat
from .BotCommandScopeChatAdministrators import BotCommandScopeChatAdministrators
from .BotCommandScopeChatMember import BotCommandScopeChatMember
from .BotName import BotName
from .BotDescription import BotDescription
from .BotShortDescription import BotShortDescription
from .MenuButton import MenuButton
from .MenuButtonCommands import MenuButtonCommands
from .MenuButtonWebApp import MenuButtonWebApp
from .MenuButtonDefault import MenuButtonDefault
from .ResponseParameters import ResponseParameters
from .InputMedia import InputMedia
from .InputMediaPhoto import InputMediaPhoto
from .InputMediaVideo import InputMediaVideo
from .InputMediaAnimation import InputMediaAnimation
from .InputMediaAudio import InputMediaAudio
from .InputMediaDocument import InputMediaDocument
from .InputFile import InputFile
from .getMe import getMe
from .sendVideoNote import sendVideoNote
from .Sticker import Sticker
from .StickerSet import StickerSet
from .MaskPosition import MaskPosition
from .InputSticker import InputSticker
from .InlineQuery import InlineQuery
from .InlineQueryResultsButton import InlineQueryResultsButton
from .InlineQueryResult import InlineQueryResult
from .InlineQueryResultArticle import InlineQueryResultArticle
from .InlineQueryResultPhoto import InlineQueryResultPhoto
from .InlineQueryResultGif import InlineQueryResultGif
from .InlineQueryResultMpeg4Gif import InlineQueryResultMpeg4Gif
from .InlineQueryResultVideo import InlineQueryResultVideo
from .InlineQueryResultAudio import InlineQueryResultAudio
from .InlineQueryResultVoice import InlineQueryResultVoice
from .InlineQueryResultDocument import InlineQueryResultDocument
from .InlineQueryResultLocation import InlineQueryResultLocation
from .InlineQueryResultVenue import InlineQueryResultVenue
from .InlineQueryResultContact import InlineQueryResultContact
from .InlineQueryResultGame import InlineQueryResultGame
from .InlineQueryResultCachedPhoto import InlineQueryResultCachedPhoto
from .InlineQueryResultCachedGif import InlineQueryResultCachedGif
from .InlineQueryResultCachedMpeg4Gif import InlineQueryResultCachedMpeg4Gif
from .InlineQueryResultCachedSticker import InlineQueryResultCachedSticker
from .InlineQueryResultCachedDocument import InlineQueryResultCachedDocument
from .InlineQueryResultCachedVideo import InlineQueryResultCachedVideo
from .InlineQueryResultCachedVoice import InlineQueryResultCachedVoice
from .InlineQueryResultCachedAudio import InlineQueryResultCachedAudio
from .InputMessageContent import InputMessageContent
from .InputTextMessageContent import InputTextMessageContent
from .InputLocationMessageContent import InputLocationMessageContent
from .InputVenueMessageContent import InputVenueMessageContent
from .InputContactMessageContent import InputContactMessageContent
from .InputInvoiceMessageContent import InputInvoiceMessageContent
from .ChosenInlineResult import ChosenInlineResult
from .SentWebAppMessage import SentWebAppMessage
from .answerShippingQuery import answerShippingQuery
from .answerPreCheckoutQuery import answerPreCheckoutQuery
from .LabeledPrice import LabeledPrice
from .Invoice import Invoice
from .ShippingAddress import ShippingAddress
from .OrderInfo import OrderInfo
from .ShippingOption import ShippingOption
from .SuccessfulPayment import SuccessfulPayment
from .ShippingQuery import ShippingQuery
from .PreCheckoutQuery import PreCheckoutQuery
from .PassportData import PassportData
from .PassportFile import PassportFile
from .EncryptedPassportElement import EncryptedPassportElement
from .EncryptedCredentials import EncryptedCredentials
from .setPassportDataErrors import setPassportDataErrors
from .PassportElementError import PassportElementError
from .PassportElementErrorDataField import PassportElementErrorDataField
from .PassportElementErrorFrontSide import PassportElementErrorFrontSide
from .PassportElementErrorReverseSide import PassportElementErrorReverseSide
from .PassportElementErrorSelfie import PassportElementErrorSelfie
from .PassportElementErrorFile import PassportElementErrorFile
from .PassportElementErrorFiles import PassportElementErrorFiles
from .PassportElementErrorTranslationFile import PassportElementErrorTranslationFile
from .PassportElementErrorTranslationFiles import PassportElementErrorTranslationFiles
from .PassportElementErrorUnspecified import PassportElementErrorUnspecified
from .Game import Game
from .CallbackGame import CallbackGame