from .utils import BaseHandler

class MessageHandler(BaseHandler):...
class EditedMessageHandler(BaseHandler):...
class ChannelPostHandler(BaseHandler):...
class EditedChannelPostHandler(BaseHandler):...
class InlineQueryHandler(BaseHandler):...
class ChosenInlineResultHandler(BaseHandler):...
class CallbackQueryHandler(BaseHandler):...
class ShippingQueryHandler(BaseHandler):...
class PreCheckoutQueryHandler(BaseHandler):...
class PollHandler(BaseHandler):...
class PollAnswerHandler(BaseHandler):...
class MyChatMemberHandler(BaseHandler):...
class ChatMemberHandler(BaseHandler):...
class ChatJoinRequestHandler(BaseHandler):...